version: "3.9"

services:
  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    restart: always
  eureka-service:
    image: eureka-server
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: always


  movie-service:
    image: movie-service
    ports:
      - "8082:8082"
    restart: always
  catalog-service:
    image: catalog-service
    ports:
      - "8084:8084"
    restart: always
 